---
deployment:
  tasks:
    # troque SEU_USUARIO pelo nome de usuario do seu cPanel
    - export DEPLOYPATH=/home/SEU_USUARIO/public_html
    - /bin/mkdir -p $DEPLOYPATH/assets/proj
    - /bin/cp -f index.html $DEPLOYPATH/
    - /bin/cp -Rf assets/. $DEPLOYPATH/assets/
